config/routes.rb
Rails.application.routes.draw do
  resource :user_session
  resources :user_passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/current.rb
module Current
  extend ActiveSupport::Concern

  included do
    attribute :person_class
    attribute session_attribute_name
    delegate person_attribute_name, to: session_attribute_name, allow_nil: true
  end

  class_methods do
    def current_for(person_class)
      self.person_class = person_class
    end
  end

  def person_attribute_name
    person_class.name.underscore.to_sym
  end

  def session_attribute_name
    "#{person_attribute_name}_session".to_sym
  end
end

app/models/current_user.rb
class CurrentUser < ActiveSupport::CurrentAttributes
  include Current

  current_for User
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_credential, dependent: :destroy
  accepts_nested_attributes_for :user_credential
  has_many :user_sessions, dependent: :destroy
end

app/models/user_credential.rb
class UserCredential < ApplicationRecord
  has_secure_password

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  belongs_to :user

  validates :user_id, uniqueness: true
  validates :email_address, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/user_session.rb
class UserSession < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  allow_browser versions: :modern
  authentication_for CurrentUser, new_person_session_url: :new_user_session_url, person_root_url: :root_url
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?

    attr_reader :current_person_class
  end

  class_methods do
    def authentication_for(current_person_class, new_person_session_url:, person_root_url:)
      @current_person_class = current_person_class
      @new_person_session_url = new_person_session_url
      @person_root_url = person_root_url
    end

    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private

  def authenticated?
    resume_session
  end

  def require_authentication
    resume_session || request_authentication
  end

  def resume_session
    current_person_class.send(underscored_session_name) || current_person_class.send("#{underscored_session_name}=", find_session_by_cookie)
  end

  def find_session_by_cookie
    session_class.find_by(id: cookies.signed[:session_id])
  end

  def request_authentication
    session[:return_to_after_authenticating] = request.url
    redirect_to @new_person_session_url
  end

  def after_authentication_url
    session.delete(:return_to_after_authenticating) || @person_root_url
  end

  def start_new_session_for(person)
    sessions = person.send("#{underscored_session_name.pluralize}")
    sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
      current_person_class.send("#{underscored_session_name}=", session)
      cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
    end
  end

  def terminate_session
    current_person_class.send(underscored_session_name).destroy
    cookies.delete(:session_id)
  end

  def session_class
    "#{current_person_class.to_s.delete_prefix("Current")}Session".constantize
  end

  def underscored_session_name
    session_class.name.underscore
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if (user = User.authenticate_by(params.permit(:email_address, :password)))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/user_passwords_controller.rb
class UserPasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    user_credential = UserCredential.find_by(email_address: params[:email_address])
    if user_credential
      UserPasswordsMailer.reset(user_credential).deliver_later
    end

    redirect_to new_user_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_user_session_path, notice: "Password has been reset."
    else
      redirect_to edit_user_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private

  def set_user_by_token
    user_credential = UserCredential.find_by_password_reset_token!(params[:token])
    @user = user_credential.user
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to new_user_password_path, alert: "Password reset link is invalid or has expired."
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    user_credential = UserCredential.authenticate_by(params.permit(:email_address, :password))
    if user_credential
      start_new_session_for user_credential.user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Day Forge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_passwords/edit.html.erb
<h1>Update your password</h1>

<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>

<%= form_with url: user_password_path(params[:token]), method: :put do |form| %>
  <%= form.password_field :password, required: true, autocomplete: "new-password", placeholder: "Enter new password", maxlength: 72 %>
  <br>
  <%= form.password_field :password_confirmation, required: true, autocomplete: "new-password", placeholder: "Repeat new password", maxlength: 72 %>
  <br>
  <%= form.submit "Save" %>
<% end %>

app/views/user_passwords/new.html.erb
<h1>Forgot your password?</h1>

<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>

<%= form_with url: user_passwords_path do |form| %>
  <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address] %>
  <br>
  <%= form.submit "Email reset instructions" %>
<% end %>

app/views/user_sessions/new.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<%= form_with url: user_session_path do |form| %>
  <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address] %>
  <br>
  <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72 %>
  <br>
  <%= form.submit "Sign in" %>
<% end %>
<br>

<%= link_to "Forgot password?", new_user_password_path %>